(()=>{"use strict";
const MT5_KEY="SAINT_BOT_ROOM_2026_SECRET",ADMIN_KEY="SAINT_BOT_ADMIN_2026_SECRET";
const NAME_KEY="sbr_names_v4",REC_KEY="sbr_records_v4",LOG_KEY="sbr_logs_v4";
let accounts=[],query="",busy=false;
const $=id=>document.getElementById(id),j=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}},p=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),money=v=>Number(v||0).toFixed(2);
const online=a=>a?.online===true||a?.connected===true||String(a?.status||"").toLowerCase()==="online";
const val=(a,...k)=>{for(const x of k)if(a?.[x]!=null)return a[x];return 0};
function toast(s,good=true){let t=$("toast");t.textContent=s;t.className="toast show "+(good?"good":"bad");setTimeout(()=>t.className="toast",2400)}
function log(account,action,status="SUCCESS",message=""){let a=j(LOG_KEY,[]);a.unshift({time:new Date().toLocaleTimeString(),account,action,status,message});p(LOG_KEY,a.slice(0,100));renderLogs()}
function renderLogs(){let a=j(LOG_KEY,[]),html=a.length?a.map(x=>`<div class="table-row"><span>${esc(x.time)}</span><span>${esc(x.account)}</span><span>${esc(x.action)}</span><span class="${x.status==="SUCCESS"?"tag":"tag off"}">${esc(x.status)}</span><span>${esc(x.message)}</span></div>`).join(""):`<div class="empty">No activity yet.</div>`;$("fullLog").innerHTML=html}
function show(screen){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$("screen-"+screen).classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.screen===screen));if(screen==="accounts")renderTable();if(screen==="controls")renderControls();if(screen==="activity")renderLogs()}
document.querySelectorAll("[data-screen]").forEach(b=>b.onclick=()=>show(b.dataset.screen));
function openModal(title,text,body){$("modalTitle").textContent=title;$("modalText").textContent=text;$("modalBody").innerHTML=body;$("modal").classList.add("show")}
function closeModal(){$("modal").classList.remove("show")}
document.querySelectorAll('[data-action="close-modal"]').forEach(b=>b.onclick=closeModal);
$("modal").onclick=e=>{if(e.target.id==="modal")closeModal()};

function openAdd(){
openModal("Add MT5 Account","Register the MT5 login in the standalone Bot Room.",`<div class="modal-form">
<label>ACCOUNT / LOGIN<input id="addId" inputmode="numeric" placeholder="1200479823"></label>
<label>ACCOUNT / CUSTOMER LABEL<input id="addLabel" placeholder="JM ACCOUNT — KATO JOHN"></label>
<button class="green-btn" id="registerBtn">REGISTER ACCOUNT</button>
</div>`);
$("registerBtn").onclick=register;
}
async function register(){
const id=$("addId").value.trim(),label=$("addLabel").value.trim()||`MT5 ACCOUNT ${id}`;
if(!id)return toast("Enter an MT5 account/login.",false);
try{let r=await fetch("/api/admin/accounts/register",{method:"POST",headers:{"Content-Type":"application/json","x-saint-admin-key":ADMIN_KEY},body:JSON.stringify({accountId:id,label})}),d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw Error(d.message||d.error||`HTTP ${r.status}`);let n=j(NAME_KEY,{});n[id]=label;p(NAME_KEY,n);closeModal();toast("Account registered.");log(id,"REGISTER ACCOUNT","SUCCESS","Account registered and activated");await refresh();show("accounts")}catch(e){toast(e.message,false);log(id||"NEW","REGISTER ACCOUNT","FAILED",e.message)}}
function render(){
const n=j(NAME_KEY,{}),r=j(REC_KEY,{});
let list=accounts.filter(a=>{let q=query.toLowerCase();return !q||[a.accountId,a.label,a.server,n[a.accountId]].join(" ").toLowerCase().includes(q)});
$("empty").hidden=list.length>0;
$("accountsList").innerHTML=list.map(a=>card(a,n,r)).join("");
document.querySelectorAll(".cmd").forEach(b=>b.onclick=()=>command(b.dataset.id,b.dataset.command));
document.querySelectorAll(".save").forEach(b=>b.onclick=()=>saveCard(b.dataset.id));
updateStats();renderTable();renderControls();
}
function card(a,n,r){
let id=String(a.accountId??a.login??a.id),name=n[id]||r[id]?.user||a.label||`MT5 ACCOUNT ${id}`,rec=r[id]||{},on=online(a),auto=a.autotrading===true||a.autoTrading===true;
return `<article class="account" data-id="${esc(id)}"><div class="account-top"><div class="identity"><div class="mt5">MT5</div><div><h3>${esc(name)}</h3><small>${esc(id)}${a.server?" • "+esc(a.server):""}</small><span class="status ${on?"":"off"}">${on?"● ONLINE":"● OFFLINE"}</span></div></div><div class="metrics"><div class="metric blue"><small>Balance</small><b>$ ${money(val(a,"balance"))}</b></div><div class="metric pink"><small>Equity</small><b>$ ${money(val(a,"equity"))}</b></div><div class="metric green"><small>Floating P/L</small><b>$ ${money(val(a,"floatingPnl","floating","profit"))}</b></div><div class="metric purple"><small>Positions</small><b>${val(a,"positions","openPositions","positionCount")}</b></div><div class="metric"><small>AutoTrading <span class="toggle ${auto?"on":""}">${auto?"ON":"OFF"}</span></small><b>${esc(a.botStatus||"UNKNOWN")}</b></div></div></div><div class="account-form"><label>USER / CUSTOMER<input class="user" value="${esc(name)}"></label><label>PROFIT MADE ($)<input class="profit" type="number" step=".01" value="${esc(rec.profit||"")}"></label><label>WITHDRAW ($)<input class="withdraw" type="number" step=".01" value="${esc(rec.withdraw||"")}"></label><label>LOSS MADE ($)<input class="loss" type="number" step=".01" value="${esc(rec.loss||"")}"></label><label>NOTES<input class="note" value="${esc(rec.note||"")}"></label><button class="save" data-id="${esc(id)}">▣ SAVE</button></div><div class="actions"><button class="action start cmd" data-id="${esc(id)}" data-command="START_BOT" ${on?"":"disabled"}>▶ START BOT</button><button class="action stop cmd" data-id="${esc(id)}" data-command="STOP_BOT" ${on?"":"disabled"}>■ STOP BOT</button><button class="action refresh cmd" data-id="${esc(id)}" data-command="REFRESH" ${on?"":"disabled"}>↻ REFRESH MT5</button><button class="action close cmd" data-id="${esc(id)}" data-command="CLOSE_ALL" ${on?"":"disabled"}>⊗ CLOSE ALL POSITIONS</button></div></article>`
}
function saveCard(id){let c=document.querySelector(`.account[data-id="${CSS.escape(id)}"]`);if(!c)return;let n=j(NAME_KEY,{}),r=j(REC_KEY,{});n[id]=c.querySelector(".user").value.trim()||`MT5 ACCOUNT ${id}`;r[id]={user:n[id],profit:c.querySelector(".profit").value,withdraw:c.querySelector(".withdraw").value,loss:c.querySelector(".loss").value,note:c.querySelector(".note").value};p(NAME_KEY,n);p(REC_KEY,r);toast("Account record saved.");log(id,"SAVE RECORD","SUCCESS","Manual account data updated");render()}
async function command(id,cmd){if(busy)return;if(cmd==="CLOSE_ALL"&&!confirm(`CLOSE ALL POSITIONS on account ${id}? This is a real MT5 action.`))return;busy=true;try{let r=await fetch(`/api/accounts/${encodeURIComponent(id)}/command`,{method:"POST",headers:{"Content-Type":"application/json","x-saint-mt5-key":MT5_KEY},body:JSON.stringify({command:cmd})}),d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw Error(d.message||d.error||`HTTP ${r.status}`);toast(`${cmd.replaceAll("_"," ")} sent to MT5.`);log(id,cmd,"SUCCESS","Command accepted by Bot Room");await refresh()}catch(e){toast(e.message,false);log(id,cmd,"FAILED",e.message)}finally{busy=false;render()}}
async function refresh(){try{let r=await fetch(`/api/accounts?t=${Date.now()}`,{headers:{"x-saint-mt5-key":MT5_KEY},cache:"no-store"});if(!r.ok)throw Error(`HTTP ${r.status}`);let d=await r.json();accounts=Array.isArray(d)?d:(d.accounts||[]);$("server").className="server";$("server").innerHTML="<i></i> SERVER ONLINE";render()}catch(e){$("server").className="server off";$("server").innerHTML="<i></i> BACKEND ERROR";console.error(e)}}
function updateStats(){let b=0,e=0,pos=0,pr=0,lo=0,w=0,onlineN=0,r=j(REC_KEY,{});accounts.forEach(a=>{b+=+val(a,"balance")||0;e+=+val(a,"equity")||0;pos+=+val(a,"positions","openPositions","positionCount")||0;if(online(a))onlineN++;let x=r[String(a.accountId)]||{};pr+=+x.profit||0;lo+=+x.loss||0;w+=+x.withdraw||0});$("sBalance").textContent="$"+money(b);$("sEquity").textContent="$"+money(e);$("sProfit").textContent="$"+money(pr);$("sLoss").textContent="$"+money(lo);$("sWithdraw").textContent="$"+money(w);$("pEquity").textContent="$"+money(e);$("pPositions").textContent=pos;$("pFloating").textContent="$"+money(accounts.reduce((z,a)=>z+(+val(a,"floatingPnl","floating","profit")||0),0));$("pAccounts").textContent=`${accounts.length} accounts`;$("pNet").textContent="$"+money(pr-lo-w)}
function renderTable(){let n=j(NAME_KEY,{});$("accountTable").innerHTML=accounts.length?accounts.map(a=>{let id=String(a.accountId),on=online(a);return `<div class="table-row"><span>${esc(id)}</span><span>${esc(n[id]||a.label||"—")}</span><span><b class="tag ${on?"":"off"}">${on?"ONLINE":"OFFLINE"}</b></span><span>${esc(a.server||"—")}</span><span class="row-actions"><button class="mini" data-admin="activate" data-id="${esc(id)}">ACTIVATE</button><button class="mini red" data-admin="deactivate" data-id="${esc(id)}">DEACTIVATE</button></span></div>`}).join(""):`<div class="empty">No registered accounts.</div>`;document.querySelectorAll("[data-admin]").forEach(b=>b.onclick=()=>adminAction(b.dataset.id,b.dataset.admin))}
async function adminAction(id,action){if(!confirm(`${action.toUpperCase()} account ${id}?`))return;try{let r=await fetch(`/api/admin/accounts/${encodeURIComponent(id)}/${action}`,{method:"POST",headers:{"x-saint-admin-key":ADMIN_KEY}}),d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw Error(d.message||d.error||`HTTP ${r.status}`);toast(`Account ${action}d.`);log(id,action.toUpperCase(),"SUCCESS","Registry updated");await refresh();show("accounts")}catch(e){toast(e.message,false);log(id,action.toUpperCase(),"FAILED",e.message)}}
function renderControls(){let n=j(NAME_KEY,{});$("controlGrid").innerHTML=accounts.length?accounts.map(a=>{let id=String(a.accountId),on=online(a);return `<div class="panel control-card"><h3>${esc(n[id]||a.label||"MT5 ACCOUNT "+id)}</h3><small>Account ${esc(id)} • ${on?"ONLINE":"OFFLINE"}</small><div class="control-buttons"><button class="action start cmd2" data-id="${id}" data-command="START_BOT" ${on?"":"disabled"}>▶ START</button><button class="action stop cmd2" data-id="${id}" data-command="STOP_BOT" ${on?"":"disabled"}>■ STOP</button><button class="action refresh cmd2" data-id="${id}" data-command="REFRESH" ${on?"":"disabled"}>↻ REFRESH</button><button class="action close cmd2" data-id="${id}" data-command="CLOSE_ALL" ${on?"":"disabled"}>⊗ CLOSE ALL</button></div></div>`}).join(""):`<div class="panel empty">No accounts connected.</div>`;document.querySelectorAll(".cmd2").forEach(b=>b.onclick=()=>command(b.dataset.id,b.dataset.command))}
function loadManual(){let x=j(REC_KEY,{}).ROOM||{};$("mUser").value=x.user||"";$("mProfit").value=x.profit||"";$("mWithdraw").value=x.withdraw||"";$("mLoss").value=x.loss||"";$("mNote").value=x.note||""}
function saveManual(){let r=j(REC_KEY,{});r.ROOM={user:$("mUser").value,profit:$("mProfit").value,withdraw:$("mWithdraw").value,loss:$("mLoss").value,note:$("mNote").value};p(REC_KEY,r);toast("Manual records saved.");log("ROOM","MANUAL RECORD","SUCCESS","Manual figures updated");updateStats()}
document.querySelectorAll("[data-action]").forEach(b=>{let a=b.dataset.action;if(a==="open-add")b.onclick=openAdd;if(a==="refresh")b.onclick=refresh;if(a==="save-manual")b.onclick=saveManual;if(a==="clear-log")b.onclick=()=>{localStorage.removeItem(LOG_KEY);renderLogs();toast("Log cleared.")}});
$("search").oninput=e=>{query=e.target.value;render()};
function clock(){let d=new Date();$("date").textContent=d.toLocaleDateString("en-GB",{weekday:"short",day:"2-digit",month:"short",year:"numeric"});$("time").textContent=d.toLocaleTimeString("en-GB")+" EAT"}
clock();setInterval(clock,1000);renderLogs();loadManual();refresh();setInterval(refresh,3000);
})();